# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a586457911d88f62e4ec86ef5fd52758e7635ac40ad85c68f51cfcb4f47c6e6946531d48d63536e860bd40b3bc3e04270a08b9bd1769cd83e5618e4ef8d42ccf

test:
  secret_key_base: 822dfe32173b3336776431841b5ec5b66ded8f48e66c1de0c11ff47b82d2f37cf99c72a85bf5b1877586a0d6690d687e06989cb9683d8b77656f6acffc82ee3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
